### ISSUE TITLE
Error with Philips AC0650/10

### ISSUE THREAD

**Issue by Manuel3190** [seydx/homebridge-philipsair-platform#173]
**Describe the bug**
Hy i try to get Philips AC0650/10 to work

**Expected behavior**
Connect to the Air and shutdown

**Logs**
[9.8.2024, 13:43:26] [PhilipsAirPlatform] Philips AIR: Purifier Active: 0
[9.8.2024, 13:43:27] [PhilipsAirPlatform] Philips AIR: An error occured during changing purifier state!
[9.8.2024, 13:43:27] [PhilipsAirPlatform] Error: Command failed: python3 /var/lib/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H 10.0.0.157 -P 5683 set pwr=0
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 111] Connection refused
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x766aa38154e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /var/lib/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H 10.0.0.157 -P 5683 set pwr=0'
}

**Environment**
- Node.js Version: v20.16.0
- Homebridge Version: 1.8.4
- Operating System: Ubuntu 24.04

**Comment by Manuel3190** [comment]
i try now a differnt Protocol 

[Air] Unable to load filter info: Error: spawnSync python3 ETIMEDOUT

Also some different error

no one here to help me?
