### ISSUE TITLE
1000i / AC1214/10 doesn't work ..

### ISSUE THREAD

**Issue by The-Paw** [seydx/homebridge-philipsair-platform#29]
14.1.2022, 17:10:40HOOBS1000i1000i: Purifier Mode: 1
14.1.2022, 17:10:41HOOBS1000i1000i: Purifier Active: 1
14.1.2022, 17:10:41HOOBS1000iWARNUNG1000i: An error occured during changing target purifier state!
14.1.2022, 17:10:41HOOBS1000iFEHLERError: Command failed: python3 /var/lib/hoobs/hoobs/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H 192.168.178.47 -P 5683 set mode=P
Traceback (most recent call last):
  File "/var/lib/hoobs/hoobs/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 6, in <module>
    from aioairctrl.__main__ import main
ModuleNotFoundError: No module named 'aioairctrl'
14.1.2022, 17:10:41HOOBS1000iWARNUNG1000i: An error occured during changing purifier state!
14.1.2022, 17:10:41HOOBS1000iFEHLERError: Command failed: python3 /var/lib/hoobs/hoobs/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H 192.168.178.47 -P 5683 set pwr=1
Traceback (most recent call last):
  File "/var/lib/hoobs/hoobs/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 6, in <module>
    from aioairctrl.__main__ import main
ModuleNotFoundError: No module named 'aioairctrl'

**Comment by The-Paw** [comment]
After installing pyaircontrol, the plugin is working .. but without pm2.5 (airquality) :-(( how can I fix it?

**Comment by The-Paw** [comment]
No Idea ??

**Comment by danielwwc** [comment]
I tested on AC1214 and it is working fine.
pm2.5 quality is expose to homekit. It is not showing as an icon but showing at climax.
The only down side is there is only On/Off. No mode switching. It is showing the fan speed in percentage.
```
{
            "active": true,
            "name": "Philips Air Purifier",
            "manufacturer": "Philips",
            "model": "AC1214",
            "serialNumber": "000000",
            "host": "192.168.0.208",
            "humidifier": false,
            "light": false,
            "temperature": false,
            "humidity": false,
            "sleepSpeed": true,
            "allergicFunc": true
}
```

<img width="532" alt="image" src="https://github.com/seydx/homebridge-philipsair-platform/assets/12077820/67294d88-d9f8-4575-8837-d39491e10c79">

**Comment by danielwwc** [comment]
there a bunch of error code though.
```
[24/12/2023, 21:01:59] [PhilipsAirPlatform] Philips Air Purifier: An error occured during changing purifier state!
[24/12/2023, 21:01:59] [PhilipsAirPlatform] Error: Command failed: python3 /var/lib/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H 192.168.0.208 -P 5683 set pwr=1
Traceback (most recent call last):
  File "/var/lib/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aioairctrl/cli.py", line 133, in async_main
    await client.shutdown()
  File "/usr/local/lib/python3.11/dist-packages/aioairctrl/coap/client.py", line 43, in shutdown
    await self._client_context.shutdown()
  File "/usr/local/lib/python3.11/dist-packages/aiocoap/protocol.py", line 320, in shutdown
    done, pending = await asyncio.wait([ri.shutdown() for ri in self.request_interfaces], timeout=3)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'TokenManager.shutdown' was never awaited
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7fbc39e200>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.11/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /var/lib/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H 192.168.0.208 -P 5683 set pwr=1'
}
```

**Comment by cson2701** [comment]
@danielwwc I have an AC2939. It works by turning on/off, showing current fan speed and light status. However, it can't change the fan speed. I get an error similar to yours. Did you solve your problem?

**Comment by BernhardBln** [comment]
> there a bunch of error code though.

Same here, with an AC2729. It actually works, the devices turns off when I turned it off in the Home app, and turns on again when I turn it on there, but I'm also seeing those errors.

Using plugin version v1.0.2, homebridge v1.9.0, node v22.15.0, python 3.11.2.

**Comment by vsenn** [comment]
I have similar experience. Plugin works basically in read-only mode on my Philips 2000i Series (AC2729). Any edit actions through HomeKit throw many unhandled exceptions and bugs in upstream Python libs.

`[6/13/2025, 11:30:08 AM] [PhilipsAirPlatform] Air Purifier: Purifier Active: 1
[6/13/2025, 11:30:12 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing purifier state!
[6/13/2025, 11:30:12 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set pwr=1
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7f83638a0e00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set pwr=1'
}
[6/13/2025, 11:30:25 AM] [UPS] NAS Consumption: Consumption: set to 62.4 W (from 52 W)
[6/13/2025, 11:30:32 AM] [PhilipsAirPlatform] Air Purifier: Purifier Rotation Speed: 60
[6/13/2025, 11:30:32 AM] [PhilipsAirPlatform] Air Purifier: Purifier Active: 1
[6/13/2025, 11:30:35 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing purifier state!
[6/13/2025, 11:30:35 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set pwr=1
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7effab830e00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set pwr=1'
}
[6/13/2025, 11:30:35 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing purifier rotation speed!
[6/13/2025, 11:30:35 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set mode=M om=2
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7fcf96724e00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:351:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set mode=M om=2'
}
[6/13/2025, 11:30:43 AM] [PhilipsAirPlatform] Air Purifier: Humidifier Active: 1
[6/13/2025, 11:30:43 AM] [PhilipsAirPlatform] Air Purifier: Humidifier Active: 1
[6/13/2025, 11:30:47 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing humidifier state!
[6/13/2025, 11:30:47 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=PH
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7f2a5ac48e00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=PH'
}
[6/13/2025, 11:30:47 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing humidifier state!
[6/13/2025, 11:30:47 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=PH
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7f4869538e00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=PH'
}
[6/13/2025, 11:30:49 AM] [PhilipsAirPlatform] Air Purifier: Humidifier State: 0
[6/13/2025, 11:30:52 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing target humidifer state!
[6/13/2025, 11:30:52 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=P
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7fdd42b9ce00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=P'
}
[6/13/2025, 11:30:52 AM] [PhilipsAirPlatform] Air Purifier: Humidifier State: 50
[6/13/2025, 11:30:55 AM] [UPS] NAS Consumption: Consumption: set to 57.2 W (from 62.4 W)
[6/13/2025, 11:30:56 AM] [PhilipsAirPlatform] Air Purifier: An error occured during changing target humidifer state!
[6/13/2025, 11:30:56 AM] [PhilipsAirPlatform] Error: Command failed: python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=PH
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 138, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 38, in create
    await obj._init()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 33, in _init
    await self._sync()
  File "/usr/local/lib/python3.12/dist-packages/aioairctrl/coap/client.py", line 54, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 832, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/protocol.py", line 884, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.NetworkError: [Errno 113] No route to host
Exception ignored in: <function RecvmsgSelectorDatagramTransport.__del__ at 0x7f606a1c4e00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 95, in __del__
  File "/usr/local/lib/python3.12/dist-packages/aiocoap/util/asyncio/recvmsg.py", line 83, in close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:351:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /homebridge/node_modules/homebridge-philipsair-platform/lib/pyaircontrol.py -H xx.xx.xx.xx -P xxxx set func=PH'
}`
